/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import system.Sistema;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import model.bean.Pessoa;
import model.bean.Curso;
import model.bean.Fez;
import model.bean.Emprego;
import model.bean.TrabalhouEm;
import model.dao.CursoDao;
import model.dao.PessoaDao;
import model.dao.EmpregoDao;
import model.dao.FezDao;
import model.dao.TrabalhouDao;
/**
 *
 * @author Venom
 */
public class Cadastro extends javax.swing.JFrame {
    
    public Sistema s;
    public CursoDao curso;
    public PessoaDao pessoa;
    public EmpregoDao  emprego;
    public FezDao  cursou;
    public TrabalhouDao  trabalhou;
    public Pessoa pessoaBEAN;
    public Curso cursoBEAN;
    public Fez fezBEAN;
    public Emprego empregoBEAN;
    public TrabalhouEm trabalhouBEAN;
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        s = new Sistema();
        curso = new CursoDao();
        pessoa = new PessoaDao();
        emprego = new EmpregoDao();
        cursou = new FezDao();
        trabalhou = new TrabalhouDao();
        pessoaBEAN = new Pessoa();
        cursoBEAN = new Curso();
        fezBEAN = new Fez();
        empregoBEAN = new Emprego();
        trabalhouBEAN = new TrabalhouEm();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextFieldCAMINHOFOTO = new javax.swing.JTextField();
        jLabelFOTO = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextFieldnome = new javax.swing.JTextField();
        jTextFieldsobrenome = new javax.swing.JTextField();
        jTextFielddata = new javax.swing.JTextField();
        jTextFieldtelefone = new javax.swing.JTextField();
        jTextFieldemail = new javax.swing.JTextField();
        jTextFieldcpf = new javax.swing.JTextField();
        jComboBoxescola = new javax.swing.JComboBox<>();
        jComboBoxingles = new javax.swing.JComboBox<>();
        jComboBoxsexo = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jTextFieldendereco = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldcurso1 = new javax.swing.JTextField();
        jTextFieldfornece1 = new javax.swing.JTextField();
        jTextFieldhoras1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldcurso2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldfornece2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldhoras2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldcurso3 = new javax.swing.JTextField();
        jTextFieldfornece3 = new javax.swing.JTextField();
        jTextFieldhoras3 = new javax.swing.JTextField();
        jTextFieldcurso4 = new javax.swing.JTextField();
        jTextFieldfornece4 = new javax.swing.JTextField();
        jTextFieldhoras4 = new javax.swing.JTextField();
        jComboBoxcertificado1 = new javax.swing.JComboBox<>();
        jComboBoxcertificado2 = new javax.swing.JComboBox<>();
        jComboBoxcertificado3 = new javax.swing.JComboBox<>();
        jComboBoxcertificado4 = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldempresa1 = new javax.swing.JTextField();
        jTextFieldcargo1 = new javax.swing.JTextField();
        jTextFieldtempo1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldempresa2 = new javax.swing.JTextField();
        jTextFieldcargo2 = new javax.swing.JTextField();
        jTextFieldtempo2 = new javax.swing.JTextField();
        jTextFieldtempo3 = new javax.swing.JTextField();
        jTextFieldcargo3 = new javax.swing.JTextField();
        jTextFieldempresa3 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextFieldtempo4 = new javax.swing.JTextField();
        jTextFieldcargo4 = new javax.swing.JTextField();
        jTextFieldempresa4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton2.setText("Adicionar Imagem");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldCAMINHOFOTO, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(299, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelFOTO, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabelFOTO, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCAMINHOFOTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Carregue sua foto", jPanel1);

        jLabel1.setText("Nome :");

        jLabel2.setText("Sobrenome :");

        jLabel3.setText("Sexo :");

        jLabel4.setText("Data de nascimento :");

        jLabel5.setText("Tefelone :");

        jLabel6.setText("Email :");

        jLabel7.setText("CPF :");

        jLabel8.setText("Escolaridade :");

        jLabel9.setText("Nível de fluência em inglês :");

        jLabel11.setText("Fale sobre você :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextFieldnome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnomeActionPerformed(evt);
            }
        });

        jTextFieldsobrenome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldsobrenome.setToolTipText("");
        jTextFieldsobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsobrenomeActionPerformed(evt);
            }
        });

        jTextFielddata.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldtelefone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldtelefone.setText("                                       ");

        jTextFieldemail.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldcpf.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jComboBoxescola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FI", "FC", "MI", "MC", "SI", "SC" }));

        jComboBoxingles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N", "B", "M", "A" }));

        jComboBoxsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel40.setText("Endereço :");

        jTextFieldendereco.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel41.setText("obs : 11 caracteres exatos");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel42.setText("DD/MM/AAAA");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel43.setText("obs: Máx 200 caracteres");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldendereco))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldsobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFielddata, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel42)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxescola, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxingles, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldtelefone)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel43)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldemail)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel41)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldsobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFielddata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxescola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxingles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jTextFieldendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Dados", jPanel2);

        jLabel12.setText("Nome do Curso :");

        jLabel13.setText("Fornecedor :");

        jLabel14.setText("Horas :");

        jLabel15.setText("Certificado :");

        jTextFieldcurso1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldfornece1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldhoras1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel16.setText("Nome do Curso :");

        jTextFieldcurso2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel17.setText("Fornecedor :");

        jTextFieldfornece2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel18.setText("Horas :");

        jTextFieldhoras2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel19.setText("Certificado :");

        jLabel20.setText("Nome do Curso :");

        jLabel21.setText("Fornecedor :");

        jLabel22.setText("Horas :");

        jLabel23.setText("Certificado :");

        jLabel24.setText("Nome do Curso :");

        jLabel25.setText("Fornecedor :");

        jLabel26.setText("Horas :");

        jLabel27.setText("Certificado :");

        jTextFieldcurso3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldfornece3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldfornece3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldfornece3ActionPerformed(evt);
            }
        });

        jTextFieldhoras3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldcurso4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldcurso4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcurso4ActionPerformed(evt);
            }
        });

        jTextFieldfornece4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldfornece4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldfornece4ActionPerformed(evt);
            }
        });

        jTextFieldhoras4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jComboBoxcertificado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "N" }));
        jComboBoxcertificado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxcertificado1ActionPerformed(evt);
            }
        });

        jComboBoxcertificado2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "N" }));

        jComboBoxcertificado3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "N" }));

        jComboBoxcertificado4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "N" }));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel44.setText("Obs : Horas no máximo 250");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldcurso1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldcurso2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldcurso3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldcurso4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldfornece1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldhoras1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxcertificado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel21)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldfornece3, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(jTextFieldfornece4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldhoras4))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldhoras3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxcertificado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxcertificado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldfornece2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldhoras2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxcertificado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 102, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldcurso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldfornece1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldhoras1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxcertificado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldhoras2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldfornece2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldcurso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBoxcertificado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jTextFieldfornece3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldhoras3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxcertificado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jTextFieldcurso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldcurso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jTextFieldfornece4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(jTextFieldhoras4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(jComboBoxcertificado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addComponent(jLabel44)
                        .addGap(49, 49, 49))))
        );

        jTabbedPane2.addTab("Cursos", jPanel3);

        jLabel28.setText("Empresa :");

        jLabel29.setText("Cargo :");

        jLabel30.setText("Tempo :");

        jTextFieldempresa1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldempresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldempresa1ActionPerformed(evt);
            }
        });

        jTextFieldcargo1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldtempo1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel31.setText("Empresa :");

        jLabel32.setText("Cargo :");

        jLabel33.setText("Tempo :");

        jLabel34.setText("Empresa :");

        jLabel35.setText("Cargo :");

        jLabel36.setText("Tempo :");

        jTextFieldempresa2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldcargo2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldtempo2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldtempo3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldtempo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtempo3ActionPerformed(evt);
            }
        });

        jTextFieldcargo3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldempresa3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel37.setText("Empresa :");

        jLabel38.setText("Cargo :");

        jLabel39.setText("Tempo :");

        jTextFieldtempo4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldcargo4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldcargo4.setText("     ");

        jTextFieldempresa4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldempresa4.setText("                                                      ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldcargo1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldtempo1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldempresa2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel32))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldempresa3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel35)))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldcargo3, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                                    .addComponent(jTextFieldcargo2)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldempresa4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldcargo4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldtempo4, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldtempo3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldtempo2)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextFieldempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jTextFieldcargo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jTextFieldtempo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextFieldempresa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jTextFieldcargo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(jTextFieldtempo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jTextFieldempresa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(jTextFieldcargo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(jTextFieldtempo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jTextFieldempresa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(jTextFieldcargo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(jTextFieldtempo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Experiência Profissional", jPanel4);

        jTabbedPane1.addTab("Informações Pessoais", jTabbedPane2);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Prencha todos os dados para seu cadastro:");

        jButton1.setText("Clique para cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser arquivo = new JFileChooser();
        arquivo.setDialogTitle("Selecione sua Foto");
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        int opc = arquivo.showOpenDialog(this);
        if(opc == JFileChooser.APPROVE_OPTION){
            File file = new File("caminho");
            file = arquivo.getSelectedFile();
            String filename = file.getAbsolutePath();
            

            
            //Caminho da foto selecionada , é importante nesse momento guarda-la no BD
           jTextFieldCAMINHOFOTO.setText(filename);
           //Adicionando o path no jtextfiel
           ImageIcon image = new ImageIcon(arquivo.getSelectedFile().getPath());
           jLabelFOTO.setIcon(new ImageIcon(image.getImage().getScaledInstance(jLabelFOTO.getWidth(), jLabelFOTO.getHeight(), Image.SCALE_DEFAULT)));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldtempo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtempo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtempo3ActionPerformed

    private void jTextFieldempresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldempresa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldempresa1ActionPerformed

    private void jComboBoxcertificado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxcertificado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxcertificado1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    String cpf =  jTextFieldcpf.getText();
    String nome = jTextFieldnome.getText();
    String sobrenome = jTextFieldsobrenome.getText();
    String sexo = jComboBoxsexo.getItemAt((jComboBoxsexo.getSelectedIndex()));
    String dataNascimento = jTextFielddata.getText();
    String email = jTextFieldemail.getText();
    String telefone = jTextFieldtelefone.getText();
    String endereco = jTextFieldendereco.getText();
    String escolaridade = jComboBoxescola.getItemAt(jComboBoxescola.getSelectedIndex());
    String nivelIngles = jComboBoxingles.getItemAt(jComboBoxingles.getSelectedIndex());
    String descriçao = jTextArea1.getText();
    
    String caminhofoto = jTextFieldCAMINHOFOTO.getText();
    
    
    pessoaBEAN.setCpf(cpf);
    pessoaBEAN.setNome(nome);
    pessoaBEAN.setSobrenome(sobrenome);
    pessoaBEAN.setSexo(sexo);
    pessoaBEAN.setDataNascimento(dataNascimento);
    pessoaBEAN.setEmail(email);
    pessoaBEAN.setTelefone(telefone);
    pessoaBEAN.setEndereco(endereco);
    pessoaBEAN.setEscolaridade(escolaridade);
    pessoaBEAN.setNivelIngles(nivelIngles);
    pessoaBEAN.setDescriçao(descriçao);
        try {
            pessoaBEAN.setFoto(s.Blobconvert(caminhofoto));
        } catch (IOException ex) {
            Logger.getLogger("Erro durante a conversão de bytes");
        }
    
    pessoa.create(pessoaBEAN);
   // JOptionPane.showConfirmDialog(this, "pessoa");
   /* String nomeCurso;
    String fornecedor;
    int horas;
    String certificado;*/
     
    if(!(jTextFieldcurso1.getText().isEmpty())){
        
    cursoBEAN.setCertificado(jComboBoxcertificado1.getItemAt(jComboBoxcertificado1.getSelectedIndex()));
    cursoBEAN.setNomeCurso(jTextFieldcurso1.getText());
    cursoBEAN.setFornecedor(jTextFieldfornece1.getText());
    cursoBEAN.setHoras(Integer.parseInt(jTextFieldhoras1.getText()));
    curso.create(cursoBEAN);  //add na tabela curso
    
    fezBEAN.setCpf(cpf);
    fezBEAN.setFornecedor(jTextFieldfornece1.getText());
    fezBEAN.setNomeCurso(jTextFieldcurso1.getText());
    cursou.create(fezBEAN); //add na tabela fez cursos
    
    }
    if(!(jTextFieldcurso2.getText().isEmpty())){
    
    cursoBEAN.setCertificado(jComboBoxcertificado2.getItemAt(jComboBoxcertificado2.getSelectedIndex()));
    cursoBEAN.setNomeCurso(jTextFieldcurso2.getText());
    cursoBEAN.setFornecedor(jTextFieldfornece2.getText());
    cursoBEAN.setHoras(Integer.parseInt(jTextFieldhoras2.getText()));
    curso.create(cursoBEAN);  //add na tabela curso
    fezBEAN.setCpf(cpf);
    fezBEAN.setFornecedor(jTextFieldfornece2.getText());
    fezBEAN.setNomeCurso(jTextFieldcurso2.getText());
    cursou.create(fezBEAN); //add na tabela fez cursos

    }
    
    if(!(jTextFieldcurso3.getText().isEmpty())){

    cursoBEAN.setCertificado(jComboBoxcertificado3.getItemAt(jComboBoxcertificado3.getSelectedIndex()));
    cursoBEAN.setNomeCurso(jTextFieldcurso3.getText());
    cursoBEAN.setFornecedor(jTextFieldfornece3.getText());
    cursoBEAN.setHoras(Integer.parseInt(jTextFieldhoras3.getText()));
    curso.create(cursoBEAN);  //add na tabela curso
    fezBEAN.setCpf(cpf);
    fezBEAN.setFornecedor(jTextFieldfornece3.getText());
    fezBEAN.setNomeCurso(jTextFieldcurso3.getText());
    cursou.create(fezBEAN); //add na tabela fez cursos
    
    }
    
    if( !(jTextFieldcurso4.getText().isEmpty()) ){
    
            cursoBEAN.setCertificado(jComboBoxcertificado4.getItemAt(jComboBoxcertificado4.getSelectedIndex()));
    cursoBEAN.setNomeCurso(jTextFieldcurso4.getText());
    cursoBEAN.setFornecedor(jTextFieldfornece4.getText());
    cursoBEAN.setHoras(Integer.parseInt(jTextFieldhoras4.getText()));
    curso.create(cursoBEAN);  //add na tabela curso
    fezBEAN.setCpf(cpf);
    fezBEAN.setFornecedor(jTextFieldfornece4.getText());
    fezBEAN.setNomeCurso(jTextFieldcurso4.getText());
    cursou.create(fezBEAN); //add na tabela fez cursos
    
    }
    
    /*String cpf;     TABELA DE LINKAGEM CURSO COM A PESSOA
    String nomeCurso;
    String fornecedor; 
    
    int idEmprego;
    String nomeEmpresa;
    String cargo;
    String tempo; */
    int id;
        if(!(jTextFieldempresa1.getText().isEmpty()) ){
        empregoBEAN.setCargo(jTextFieldcargo1.getText() );
        empregoBEAN.setNomeEmpresa(jTextFieldempresa1.getText());
        empregoBEAN.setTempo(jTextFieldtempo1.getText());
        
        emprego.create(empregoBEAN);
        id = emprego.procId(jTextFieldempresa1.getText(),jTextFieldcargo1.getText(), jTextFieldtempo1.getText());
        
       // JOptionPane.showMessageDialog(this, id);
    //empregoBEAN.setIdEmprego(id);

        
        trabalhouBEAN.setCpf(cpf);
        trabalhouBEAN.setIdEmp(id);
        trabalhou.create(trabalhouBEAN);
        
        }        
 
        if(!(jTextFieldempresa2.getText().isEmpty()) ){
        empregoBEAN.setCargo(jTextFieldcargo2.getText() );
        empregoBEAN.setNomeEmpresa(jTextFieldempresa2.getText());
        empregoBEAN.setTempo(jTextFieldtempo2.getText());
        id = emprego.procId(jTextFieldempresa2.getText(),jTextFieldcargo2.getText(), jTextFieldtempo2.getText());
        //empregoBEAN.setIdEmprego(id);
        emprego.create(empregoBEAN);
        
        trabalhouBEAN.setCpf(cpf);
        trabalhouBEAN.setIdEmp(id);
        trabalhou.create(trabalhouBEAN);
     }
     
      if( !(jTextFieldempresa3.getText().isEmpty()) ){
          
                  empregoBEAN.setCargo(jTextFieldcargo3.getText() );
        empregoBEAN.setNomeEmpresa(jTextFieldempresa3.getText());
        empregoBEAN.setTempo(jTextFieldtempo3.getText());
        id = emprego.procId(jTextFieldempresa3.getText(),jTextFieldcargo3.getText(), jTextFieldtempo3.getText());
        //empregoBEAN.setIdEmprego(id);
        emprego.create(empregoBEAN);
        
        trabalhouBEAN.setCpf(cpf);
        trabalhouBEAN.setIdEmp(id);
        trabalhou.create(trabalhouBEAN);
      }
      
       if( !(jTextFieldempresa4.getText().isEmpty()) ){
           
                   empregoBEAN.setCargo(jTextFieldcargo4.getText() );
        empregoBEAN.setNomeEmpresa(jTextFieldempresa4.getText());
        empregoBEAN.setTempo(jTextFieldtempo4.getText());
        id = emprego.procId(jTextFieldempresa4.getText(),jTextFieldcargo4.getText(), jTextFieldtempo4.getText());
        //empregoBEAN.setIdEmprego(id);
        emprego.create(empregoBEAN);
        
        trabalhouBEAN.setCpf(cpf);
        trabalhouBEAN.setIdEmp(id);
        trabalhou.create(trabalhouBEAN);
       
       }
        
    
       /*    private String cpf;   TABELA DE LINKAGEM TRABALHOU EM
    private int idEmp;
*/
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldfornece4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldfornece4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldfornece4ActionPerformed

    private void jTextFieldnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnomeActionPerformed

    private void jTextFieldsobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsobrenomeActionPerformed

    private void jTextFieldcurso4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcurso4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcurso4ActionPerformed

    private void jTextFieldfornece3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldfornece3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldfornece3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxcertificado1;
    private javax.swing.JComboBox<String> jComboBoxcertificado2;
    private javax.swing.JComboBox<String> jComboBoxcertificado3;
    private javax.swing.JComboBox<String> jComboBoxcertificado4;
    private javax.swing.JComboBox<String> jComboBoxescola;
    private javax.swing.JComboBox<String> jComboBoxingles;
    private javax.swing.JComboBox<String> jComboBoxsexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFOTO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldCAMINHOFOTO;
    private javax.swing.JTextField jTextFieldcargo1;
    private javax.swing.JTextField jTextFieldcargo2;
    private javax.swing.JTextField jTextFieldcargo3;
    private javax.swing.JTextField jTextFieldcargo4;
    private javax.swing.JTextField jTextFieldcpf;
    private javax.swing.JTextField jTextFieldcurso1;
    private javax.swing.JTextField jTextFieldcurso2;
    private javax.swing.JTextField jTextFieldcurso3;
    private javax.swing.JTextField jTextFieldcurso4;
    private javax.swing.JTextField jTextFielddata;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldempresa1;
    private javax.swing.JTextField jTextFieldempresa2;
    private javax.swing.JTextField jTextFieldempresa3;
    private javax.swing.JTextField jTextFieldempresa4;
    private javax.swing.JTextField jTextFieldendereco;
    private javax.swing.JTextField jTextFieldfornece1;
    private javax.swing.JTextField jTextFieldfornece2;
    private javax.swing.JTextField jTextFieldfornece3;
    private javax.swing.JTextField jTextFieldfornece4;
    private javax.swing.JTextField jTextFieldhoras1;
    private javax.swing.JTextField jTextFieldhoras2;
    private javax.swing.JTextField jTextFieldhoras3;
    private javax.swing.JTextField jTextFieldhoras4;
    private javax.swing.JTextField jTextFieldnome;
    private javax.swing.JTextField jTextFieldsobrenome;
    private javax.swing.JTextField jTextFieldtelefone;
    private javax.swing.JTextField jTextFieldtempo1;
    private javax.swing.JTextField jTextFieldtempo2;
    private javax.swing.JTextField jTextFieldtempo3;
    private javax.swing.JTextField jTextFieldtempo4;
    // End of variables declaration//GEN-END:variables
}
